import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <header
        className="w-full h-96 bg-[url('/corn.jpg')] bg-cover bg-center flex justify-center items-center">
        <div className="flex flex-col justify-center items-center">
            <h1 className=" text-center text-5xl text-white font-bold drop-shadow-lg">WELCOME TO
            <span className="text-amber-500">TOMORROWLAND</span>
            </h1>
            <p className="mt-5 text-center text-lg text-white opacity-70">Possibilities of the future</p>
            <Link className="mt-8 px-12 py-3 bg-gradient-to-r from-amber-500 to-red-600 hover:from-amber-600 hover:to-red-700 text-xl text-white/70 font-semibold drop-shadow-lg rounded-full"
                href="/apply">Apply today!</Link>
        </div>
      </header>

        <div className={styles.grid}>
          <Link href="/static-example" className={styles.card}>
            <h2>Static Example &rarr;</h2>
            <p>See how Next builds hyper-fast static pages when data doesn't change.</p>
          </Link>

          <a href="/review" className={styles.card}>
            <h2>Review Applications &rarr;</h2>
            <p>Lets see what a serverless frontend app looks like!</p>
          </a>

          <a
            href="/apply"
            className={styles.card}
          >
            <h2>Post DB Data &rarr;</h2>
            <p>See how easy it is to talk to the DB</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
